package com.oai.perfpilot

data class PerfParam(
    val key: String,
    val title: String,
    val category: String,
    val resourceId: Int?,
    val paths: List<String> = emptyList(),
    val min: Int? = null,
    val max: Int? = null,
    val description: String,
    val writable: Boolean = true
)

object PerfCatalog {
    val all: List<PerfParam> = listOf(
        PerfParam("fpsgo_enable", "FPSGO 总开关", "FPSGO / CFP", 0x02004000, listOf("/sys/kernel/fpsgo/common/fpsgo_enable"), 0, 1, "联发科 FPSGO 总开关。", true),
        PerfParam("fpsgo_force_onoff", "FPSGO 强制开关", "FPSGO / CFP", 0x02004100, listOf("/sys/kernel/fpsgo/common/force_onoff"), 0, 1, "强制 FPSGO 开/关。", true),
        PerfParam("fpsgo_mfrc_active", "MFRC Active", "FPSGO / CFP", 0x02004e00, listOf("/sys/kernel/fpsgo/composer/mfrc_active"), 0, 1, "FPSGO MFRC 活跃状态控制。", true),
        PerfParam("cfp_enable", "CFP 预测式升频", "FPSGO / CFP", 0x03008000, listOf("/sys/module/mtk_fpsgo/parameters/cfp_onoff"), 0, 1, "CPU Frequency Policy 开关。", true),
        PerfParam("cfp_polling", "CFP 轮询间隔", "FPSGO / CFP", 0x03008100, listOf("/sys/module/mtk_fpsgo/parameters/cfp_polling_ms"), 1, 5000, "CFP 负载轮询周期，单位 ms。", true),
        PerfParam("cfp_up_loading", "CFP 升频负载阈值", "FPSGO / CFP", 0x03008200, listOf("/sys/module/mtk_fpsgo/parameters/cfp_up_loading"), 0, 100, "达到该负载附近时更积极升频。", true),
        PerfParam("cfp_down_loading", "CFP 降频负载阈值", "FPSGO / CFP", 0x03008300, listOf("/sys/module/mtk_fpsgo/parameters/cfp_down_loading"), 0, 100, "低于该负载附近时允许降频。", true),
        PerfParam("cfp_up_time", "CFP 升频时间窗口", "FPSGO / CFP", 0x03008400, listOf("/sys/module/mtk_fpsgo/parameters/cfp_up_time"), 0, 1000, "升频响应时间窗口。", true),
        PerfParam("cfp_down_time", "CFP 降频时间窗口", "FPSGO / CFP", 0x03008500, listOf("/sys/module/mtk_fpsgo/parameters/cfp_down_time"), 0, 1000, "降频响应时间窗口。", true),
        PerfParam("fpsgo_llf_th", "轻负载阈值", "FPSGO / CFP", 0x02044000, emptyList(), 0, 100, "FPSGO Low Loading Framework 阈值，优先走 PowerHAL。", true),
        PerfParam("fpsgo_llf_policy", "轻负载策略", "FPSGO / CFP", 0x02044100, emptyList(), 0, 8, "FPSGO 轻负载策略枚举。", true),
        PerfParam("fpsgo_llf_policy_param", "轻负载策略参数", "FPSGO / CFP", 0x02044200, emptyList(), 0, 10000, "FPSGO 轻负载策略参数。", true),
        PerfParam("fbt_filterframe", "帧过滤功能", "FPSGO / CFP", 0x02064700, emptyList(), 0, 1, "过滤异常帧，降低调度抖动。", true),
        PerfParam("fstb_gpu_slowdown", "GPU Slowdown Check", "FPSGO / CFP", 0x02080200, listOf("/sys/kernel/fpsgo/fstb/gpu_slowdown_check"), 0, 1, "检测 GPU 降速情况。", true),
        PerfParam("fbt_boost_affinity", "Boost Affinity", "FBT / XGF", 0x0205c000, emptyList(), 0, 1, "渲染/关键线程绑核策略开关。", true),
        PerfParam("fbt_cpumask_heavy", "FBT 重型任务 CPU Mask", "FBT / XGF", 0x0205c700, emptyList(), 0, null, "重型任务 CPU 掩码，按设备拓扑配置。", true),
        PerfParam("fbt_cpumask_second", "FBT 次要任务 CPU Mask", "FBT / XGF", 0x0205c900, emptyList(), 0, null, "次要任务 CPU 掩码。", true),
        PerfParam("fbt_cpumask_others", "FBT 其他任务 CPU Mask", "FBT / XGF", 0x0205cb00, emptyList(), 0, null, "其他任务 CPU 掩码。", true),
        PerfParam("fbt_limit_cfreq", "FBT CPU 频率限制", "FBT / XGF", 0x02064000, emptyList(), 0, null, "FBT CPU 频率限制资源。", true),
        PerfParam("fbt_limit_rfreq", "FBT 渲染频率限制", "FBT / XGF", 0x02064100, emptyList(), 0, null, "FBT render frequency 限制。", true),
        PerfParam("fbt_limit_cfreq_m", "FBT 中核 CPU 频率限制", "FBT / XGF", 0x02064200, emptyList(), 0, null, "FBT 中核 CPU 频率限制。", true),
        PerfParam("fbt_limit_rfreq_m", "FBT 中核渲染频率限制", "FBT / XGF", 0x02064300, emptyList(), 0, null, "FBT 中核 render frequency 限制。", true),
        PerfParam("fbt_ceiling", "FBT Ceiling 开关", "FBT / XGF", 0x02064400, emptyList(), 0, 1, "频率上限功能开关。", true),
        PerfParam("minitop_enable", "Minitop 开关", "FBT / XGF", 0x02064500, emptyList(), 0, 1, "轻量关键任务识别器开关。", true),
        PerfParam("minitop_heavy", "Minitop 重型任务阈值", "FBT / XGF", 0x02064600, emptyList(), 0, 100, "Minitop 重负载识别阈值。", true),
        PerfParam("eara_min_b", "EARA 大核最小频率", "FBT / XGF", 0x02064a00, emptyList(), 0, null, "EARA 为大核保留的最小频率资源。", true),
        PerfParam("eara_min_m", "EARA 中核最小频率", "FBT / XGF", 0x02064b00, emptyList(), 0, null, "EARA 为中核保留的最小频率资源。", true),
        PerfParam("eara_min_enable", "EARA 最小频率开关", "FBT / XGF", 0x02064c00, emptyList(), 0, 1, "EARA 最小频率控制开关。", true),
        PerfParam("xgf_spid", "XGF 特殊进程配置", "FBT / XGF", 0x02060000, emptyList(), 0, 1, "XGF 特殊进程配置开关。", true),
        PerfParam("xgf_force_perf_min", "XGF 强制最小性能", "FBT / XGF", 0x02060500, emptyList(), 0, 1, "XGF 强制设置最小性能。", true),
        PerfParam("xgf_dep_frames", "XGF 依赖分析帧数", "FBT / XGF", 0x02048000, emptyList(), 1, 120, "用于预测的历史帧数量。", true),
        PerfParam("xgf_sp_name_id", "XGF 特殊进程标识", "FBT / XGF", 0x02048100, emptyList(), 0, null, "特殊进程标识资源。", true),
        PerfParam("xgf_sp_ck_period", "XGF 特殊进程检查周期", "FBT / XGF", 0x02048300, emptyList(), 1, 10000, "特殊进程扫描周期。", true),
        PerfParam("xgf_sub_queue", "XGF 附加队列监测", "FBT / XGF", 0x02048400, emptyList(), 0, 10000, "附加 queue/dequeue 监测周期。", true),
        PerfParam("xgf_ema", "XGF EMA 平滑因子", "FBT / XGF", 0x02048500, emptyList(), 1, 1000, "XGF 负载平滑因子。", true),
        PerfParam("xgf_force_no_subq", "XGF 禁用附加队列监测", "FBT / XGF", 0x02048900, emptyList(), 0, 1, "强制禁用附加队列监测。", true),
        PerfParam("ged_margin", "GED DVFS Margin", "GED GPU", 0x00c0c100, listOf("/sys/kernel/ged/hal/dvfs_margin_value"), 0, 100, "GPU DVFS 性能余量。", true),
        PerfParam("ged_timer_margin", "GED Timer DVFS Margin", "GED GPU", 0x00c0c200, listOf("/sys/kernel/ged/hal/timer_base_dvfs_margin"), 0, 100, "基于时间的 GPU DVFS 余量。", true),
        PerfParam("ged_loading_step", "GED Loading DVFS Step", "GED GPU", 0x00c0c300, listOf("/sys/kernel/ged/hal/loading_base_dvfs_step"), 0, 100, "GPU 负载 DVFS 步进。", true),
        PerfParam("ged_loading_mode", "GED Loading Mode", "GED GPU", 0x00c0c600, listOf("/sys/kernel/ged/hal/dvfs_loading_mode"), 0, 4, "GPU DVFS 负载计算模式。", true),
        PerfParam("ged_workload_mode", "GED Workload Mode", "GED GPU", 0x00c0c700, listOf("/sys/kernel/ged/hal/dvfs_workload_mode"), 0, 4, "GPU workload 检测模式。", true),
        PerfParam("gpu_bw_hint", "GPU 带宽模式提示", "GED GPU", 0x00c18000, emptyList(), 0, 8, "GPU 内存带宽模式提示。", true),
        PerfParam("gpu_dcs", "GPU DCS 动态核心", "GED GPU", 0x00c1c000, listOf("/sys/kernel/ged/hal/dcs_mode"), 0, 4, "GPU Dynamic Core Scaling 策略。", true),
        PerfParam("ged_window", "GED Loading Window", "GED GPU", 0x00c28100, listOf("/sys/kernel/ged/hal/loading_base_window_size"), 1, 10000, "GPU 负载计算窗口大小。", true),
        PerfParam("ged_stride", "GED Loading Stride", "GED GPU", 0x00c28200, listOf("/sys/kernel/ged/hal/loading_base_stride_size"), 1, 10000, "GPU 负载计算步进大小。", true),
        PerfParam("ged_force_loading", "GED Force Loading Base", "GED GPU", 0x00c2c500, listOf("/sys/kernel/ged/hal/force_loading_base"), 0, 1, "强制使用 loading base。", true),
        PerfParam("foreground_latency", "前台优先空闲核", "调度 / UClamp", 0x01404100, listOf("/dev/cpuctl/foreground/cpu.uclamp.latency_sensitive"), 0, 1, "前台任务组 latency_sensitive。", true),
        PerfParam("foreground_min", "前台最小利用率", "调度 / UClamp", 0x01408100, listOf("/dev/cpuctl/foreground/cpu.uclamp.min"), 0, 100, "前台任务组 uclamp.min。", true),
        PerfParam("foreground_max", "前台最大利用率", "调度 / UClamp", 0x01408700, listOf("/dev/cpuctl/foreground/cpu.uclamp.max"), 0, 100, "前台任务组 uclamp.max。", true),
        PerfParam("background_latency", "后台优先空闲核", "调度 / UClamp", 0x01404200, listOf("/dev/cpuctl/background/cpu.uclamp.latency_sensitive"), 0, 1, "后台任务组 latency_sensitive。", true),
        PerfParam("background_min", "后台最小利用率", "调度 / UClamp", 0x01408200, listOf("/dev/cpuctl/background/cpu.uclamp.min"), 0, 100, "后台任务组 uclamp.min。", true),
        PerfParam("background_max", "后台最大利用率", "调度 / UClamp", 0x01408800, listOf("/dev/cpuctl/background/cpu.uclamp.max"), 0, 100, "后台任务组 uclamp.max。", true),
        PerfParam("topapp_latency", "Top-App优先空闲核", "调度 / UClamp", 0x01404300, listOf("/dev/cpuctl/top-app/cpu.uclamp.latency_sensitive"), 0, 1, "Top-App任务组 latency_sensitive。", true),
        PerfParam("topapp_min", "Top-App最小利用率", "调度 / UClamp", 0x01408300, listOf("/dev/cpuctl/top-app/cpu.uclamp.min"), 0, 100, "Top-App任务组 uclamp.min。", true),
        PerfParam("topapp_max", "Top-App最大利用率", "调度 / UClamp", 0x01408900, listOf("/dev/cpuctl/top-app/cpu.uclamp.max"), 0, 100, "Top-App任务组 uclamp.max。", true),
        PerfParam("rt_latency", "实时任务优先空闲核", "调度 / UClamp", 0x01404400, listOf("/dev/cpuctl/rt/cpu.uclamp.latency_sensitive"), 0, 1, "实时任务任务组 latency_sensitive。", true),
        PerfParam("rt_min", "实时任务最小利用率", "调度 / UClamp", 0x01408400, listOf("/dev/cpuctl/rt/cpu.uclamp.min"), 0, 100, "实时任务任务组 uclamp.min。", true),
        PerfParam("rt_max", "实时任务最大利用率", "调度 / UClamp", 0x01408a00, listOf("/dev/cpuctl/rt/cpu.uclamp.max"), 0, 100, "实时任务任务组 uclamp.max。", true),
        PerfParam("system_latency", "系统任务优先空闲核", "调度 / UClamp", 0x01404600, listOf("/dev/cpuctl/system/cpu.uclamp.latency_sensitive"), 0, 1, "系统任务任务组 latency_sensitive。", true),
        PerfParam("system_min", "系统任务最小利用率", "调度 / UClamp", 0x01408500, listOf("/dev/cpuctl/system/cpu.uclamp.min"), 0, 100, "系统任务任务组 uclamp.min。", true),
        PerfParam("system_max", "系统任务最大利用率", "调度 / UClamp", 0x01408b00, listOf("/dev/cpuctl/system/cpu.uclamp.max"), 0, 100, "系统任务任务组 uclamp.max。", true),
        PerfParam("sysbg_latency", "系统后台优先空闲核", "调度 / UClamp", 0x01404700, listOf("/dev/cpuctl/system-background/cpu.uclamp.latency_sensitive"), 0, 1, "系统后台任务组 latency_sensitive。", true),
        PerfParam("sysbg_min", "系统后台最小利用率", "调度 / UClamp", 0x01408c00, listOf("/dev/cpuctl/system-background/cpu.uclamp.min"), 0, 100, "系统后台任务组 uclamp.min。", true),
        PerfParam("sysbg_max", "系统后台最大利用率", "调度 / UClamp", 0x01408d00, listOf("/dev/cpuctl/system-background/cpu.uclamp.max"), 0, 100, "系统后台任务组 uclamp.max。", true),
        PerfParam("cpu_dynamic_policy", "CPU 核心动态策略", "内存 / 系统", 0x0143c100, emptyList(), 0, 8, "PowerHAL CPU core dynamic policy。", true),
        PerfParam("multi_power_balance", "多核功耗平衡", "内存 / 系统", 0x10000400, emptyList(), 0, 8, "多处理器性能/功耗平衡。", true),
        PerfParam("cpu_freq_perf_mode", "CPU 频率性能模式", "内存 / 系统", 0x00414000, emptyList(), 0, 8, "CPU 频率性能策略。", true),
        PerfParam("cpu_core_perf_mode", "CPU 核心性能模式", "内存 / 系统", 0x00808000, emptyList(), 0, 8, "CPU 核心性能策略。", true),
        PerfParam("cpu_interconnect", "CPU/CCI 互联策略", "内存 / 系统", 0x00410000, emptyList(), 0, null, "CPU/CCI interconnect 性能资源。", true),
        PerfParam("game_mode", "PowerHAL 游戏模式", "内存 / 系统", 0x03404200, emptyList(), 0, 1, "联发科 PowerHAL 游戏模式开关。", true),
        PerfParam("game_marker", "游戏场景标记", "内存 / 系统", 0x10000300, emptyList(), 0, 1, "厂商游戏场景标记。", true),
        PerfParam("task_latency", "任务响应延迟", "内存 / 系统", 0x10000500, emptyList(), 0, null, "系统任务响应时间/延迟策略。", true),
        PerfParam("thp_mode", "THP 工作模式", "内存 / 系统", 0x10000200, emptyList(), 0, 3, "Transparent Huge Page 厂商工作模式。", true),
        PerfParam("cpu_dma_latency", "CPU DMA 延迟 QoS", "内存 / 系统", 0x01c3c200, emptyList(), 0, null, "CPU DMA latency QoS。", true),
        PerfParam("dram_floor", "DRAM OPP Floor", "内存 / 系统", 0x01010700, emptyList(), 0, null, "DRAM 最低 OPP 限制。", true),
        PerfParam("dram_ceil", "DRAM OPP Ceiling", "内存 / 系统", 0x01010800, emptyList(), 0, null, "DRAM 最高 OPP 限制。", true),
        PerfParam("dram_qos", "DRAM QoS 模式", "内存 / 系统", 0x01010900, emptyList(), 0, 8, "DRAM DVFS QoS 模式。", true),
        PerfParam("dram_passive", "DRAM CM Passive", "内存 / 系统", 0x01014500, emptyList(), 0, 1, "CPU-DRAM 协同策略。", true),
        PerfParam("dram_thermal_hint", "DRAM Thermal Hint", "内存 / 系统", 0x01014900, listOf("/sys/kernel/thermal/thermal_hint"), 0, 1, "内存子系统 thermal hint。", true),
        PerfParam("dram_qosmm", "DRAM QoS-MM", "内存 / 系统", 0x01058000, emptyList(), 0, 8, "多媒体内存 QoS 模式。", true),
        PerfParam("dram_cpu_target", "内存优化 CPU Target Load", "内存 / 系统", 0x01054100, emptyList(), 0, 100, "内存优化中的 CPU target load。", true),
        PerfParam("touch_enable", "触控升频开关", "触控 / 启动", 0x03408500, listOf("/proc/touch_boost/enable"), 0, 1, "触控时启用厂商 boost。", true),
        PerfParam("touch_duration", "触控 Boost 持续时间", "触控 / 启动", 0x03408100, emptyList(), 0, 5000, "触控 boost 持续时间。", true),
        PerfParam("touch_eas_ta", "触控 Top-App EAS Boost", "触控 / 启动", 0x03408300, emptyList(), 0, 100, "触控时 Top-App EAS boost。", true),
        PerfParam("touch_cluster0", "触控小核 OPP", "触控 / 启动", 0x03408800, emptyList(), 0, 31, "触控时 cluster0 OPP；31 常表示不强制。", true),
        PerfParam("touch_cluster1", "触控中核 OPP", "触控 / 启动", 0x03408900, emptyList(), 0, 31, "触控时 cluster1 OPP。", true),
        PerfParam("touch_cluster2", "触控大核 OPP", "触控 / 启动", 0x03408a00, emptyList(), 0, 31, "触控时 cluster2 OPP。", true),
        PerfParam("touch_eas_fg", "触控前台 EAS Boost", "触控 / 启动", 0x03408c00, emptyList(), 0, 100, "触控时 Foreground EAS boost。", true),
        PerfParam("touch_idle_ta", "触控 Top-App 优先空闲核", "触控 / 启动", 0x03408d00, emptyList(), 0, 1, "触控时 Top-App prefer idle。", true),
        PerfParam("touch_idle_fg", "触控前台优先空闲核", "触控 / 启动", 0x03408e00, emptyList(), 0, 1, "触控时 Foreground prefer idle。", true),
        PerfParam("touch_boost_up", "触控 Boost 升频", "触控 / 启动", 0x03408f00, emptyList(), 0, 1, "触控升频使能。", true),
        PerfParam("touch_boost_down", "触控 Boost 降频", "触控 / 启动", 0x03409000, emptyList(), 0, 1, "触控降频使能。", true),
        PerfParam("launch_target", "启动时间目标", "触控 / 启动", 0x0300c100, emptyList(), 50, 5000, "应用启动优化目标时间，单位 ms。", true),
        PerfParam("launch_c2_max", "启动时大核最高频", "触控 / 启动", 0x0300c200, emptyList(), 300000, 5000000, "启动场景高性能集群最高频资源。", true),
        PerfParam("launch_c2_ratio", "启动时大核性能占比", "触控 / 启动", 0x0300c300, emptyList(), 0, 100, "启动期间高性能集群预算比例。", true),
        PerfParam("launch_c2_opp", "启动时大核 OPP 空间", "触控 / 启动", 0x0300c400, emptyList(), 1, 32, "启动期间允许的 OPP 空间。", true),
        PerfParam("c2ps_mode", "C2PS UClamp 策略模式", "C2PS", 0x03800000, emptyList(), 0, 8, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_up", "C2PS UClamp 上升边界", "C2PS", 0x03800100, emptyList(), 0, 100, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_down", "C2PS UClamp 下降边界", "C2PS", 0x03800200, emptyList(), 0, 100, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_base", "C2PS UClamp 基础更新", "C2PS", 0x03800300, emptyList(), 0, 100, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_window", "C2PS 进程时间窗口", "C2PS", 0x03804000, emptyList(), 1, 10000, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_bg_little", "C2PS 后台小核上升边界", "C2PS", 0x03808000, emptyList(), 0, 100, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_bg_mid", "C2PS 后台中核上升边界", "C2PS", 0x03808100, emptyList(), 0, 100, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_bg_big", "C2PS 后台大核上升边界", "C2PS", 0x03808200, emptyList(), 0, 100, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_idle_alert", "C2PS 后台空闲率警报", "C2PS", 0x03808300, emptyList(), 0, 100, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_bg_base", "C2PS 后台基础更新", "C2PS", 0x03808400, emptyList(), 0, 100, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_monitor", "C2PS 后台监控持续时间", "C2PS", 0x03808500, emptyList(), 0, 10000, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_danger_idle", "C2PS 后台危险空闲率", "C2PS", 0x03808600, emptyList(), 0, 100, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_fast", "C2PS 后台快速更新", "C2PS", 0x03808700, emptyList(), 0, 1, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_slot", "C2PS 后台策略 Slot", "C2PS", 0x03808800, emptyList(), 0, null, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("c2ps_um_slot", "C2PS 后台 UM Slot", "C2PS", 0x0380c000, emptyList(), 0, null, "联发科 C2PS 厂商性能资源。", true),
        PerfParam("magt_thermal", "MAGT 热感知阈值", "热感知（只读）", 0x03018000, emptyList(), null, null, "原软件中的厂商热感知资源。PerfPilot 仅展示/诊断，不修改系统热保护。", false),
        PerfParam("magt_fpsdrop", "MAGT FPS 下降阈值", "热感知（只读）", 0x03018100, emptyList(), null, null, "原软件中的厂商热感知资源。PerfPilot 仅展示/诊断，不修改系统热保护。", false),
        PerfParam("magt_avg_current", "MAGT 建议平均电流", "热感知（只读）", 0x03018200, emptyList(), null, null, "原软件中的厂商热感知资源。PerfPilot 仅展示/诊断，不修改系统热保护。", false),
        PerfParam("magt_max_current", "MAGT 建议最大电流", "热感知（只读）", 0x03018300, emptyList(), null, null, "原软件中的厂商热感知资源。PerfPilot 仅展示/诊断，不修改系统热保护。", false),
        PerfParam("magt_target_temp", "MAGT 目标 FPS 温度", "热感知（只读）", 0x03018400, emptyList(), null, null, "原软件中的厂商热感知资源。PerfPilot 仅展示/诊断，不修改系统热保护。", false),
        PerfParam("magt_light_thermal", "MAGT 轻度热阈值", "热感知（只读）", 0x03018500, emptyList(), null, null, "原软件中的厂商热感知资源。PerfPilot 仅展示/诊断，不修改系统热保护。", false),
        PerfParam("magt_workers", "MAGT 建议工作线程数", "热感知（只读）", 0x03018600, emptyList(), null, null, "原软件中的厂商热感知资源。PerfPilot 仅展示/诊断，不修改系统热保护。", false),
    )

    val categories: List<String> by lazy { all.map { it.category }.distinct() }
    fun inCategory(category: String): List<PerfParam> = all.filter { it.category == category }
    fun find(key: String): PerfParam? = all.firstOrNull { it.key == key }
}
